### ISSUE TITLE
Training at once for all classes

### ISSUE THREAD

**Issue by nguptaHQ** [ternaus/kaggle_dstl_submission#12]
I have a problem statement in which there are total 16 classes. I trained with Segnet with all classes at once. Results are not that good.
And I saw your solution. 
I wanted to know which one is more suitable:
 1. training for each of the classes separately
 2. training for all classes at once.

Did you tried training of all classes at once. I just wanted to know you experience and suggestions regarding this.

**Comment by johnny-salz** [comment]
Training of all classes at once is fine and it is usually done this way in real tasks. It was competition settings and severe class imbalance which forced us to treat each class independently. Also, there are some research that shows that usually networks trained on harder tasks work better in simple cases. So, I'd suggest training all at once (and use pretrained network, always)
