### ISSUE TITLE
RGB implementation

### ISSUE THREAD

**Issue by zainabideenrehman** [ternaus/kaggle_dstl_submission#15]
I want to implement your pre-trained model of DSTL competition only on RGB images. I don't have data set of other band images for my satellite imagery application. Is it possible to test only RGB images using your pre-trained model?

**Comment by ternaus** [comment]
I do not think that it will work. You may just retrain the model, it would be much faster. Data is available at the Kaggle website.

We worked on this problem more than a year ago. Everything is changing so fast. There are much better ways to perform segmentation for satellite images.

**Comment by zainabideenrehman** [comment]
Thanks for your time sir. If possible, kindly share some links where we can
get pre-trained models or any other usefull help regarding segmentation for
satellite images. I will be very thankful to you.
Regards
Zain ul Abideen
Software Developer

**Comment by LydiaSIM** [comment]
> 
> 
> I want to implement your pre-trained model of DSTL competition only on RGB images. I don't have data set of other band images for my satellite imagery application. Is it possible to test only RGB images using your pre-trained model?

Hello! Do you have solve your problem ?
