### ISSUE TITLE
Object detection question

### ISSUE THREAD

**Issue by tdyku** [ternaus/kaggle_dstl_submission#16]
Hi!
Sorry for raising an issue, I found it as a way of reaching out to you.
I am very impressed by your solutions for many image segmentation competitions, where participants are provided with image and ground-truth labels.
However I wanted to ask about your approach in cases when ground truth is only point, not mask (for example https://www.datasciencechallenge.org/challenges/1/safe-passage competition). 
Could you reveal your appropach to such a problem? How to prepare masks in such a case, what kind of networks to use? 

Kind regards,
Tomasz

**Comment by ternaus** [comment]
Probably, if you would reach me out on the LinkedIn it would be faster.

There are 2 main approaches:

1. Label bounding boxes yourself for the train set and use these labels with Faster RCNN, YOLO, SSD, etc (That is what I did in SafePassage)
2. Assign gaussian to the dot and use segmentation approach. The peak of the predicted heat map will correspond to the centers of the objects.

I hope this helps.
