### ISSUE TITLE
TypeError: 'compression_opts' is an invalid keyword argument for this function(cache_train.py)

### ISSUE THREAD

**Issue by yanghuiyun** [ternaus/kaggle_dstl_submission#17]
When I run your code -cache_train.py in spyder,it told that --TypeError: 'compression_opts' is an invalid keyword argument for this function(I have installed all packages what we need ),Can you tell me what should I do?
Thanks

**Comment by johnny-salz** [comment]
You may try to remove argument compression_opts, it doesn't have any crucial meaning.
