### ISSUE TITLE
make prediction on buildings is failing

### ISSUE THREAD

**Issue by degiorgig** [ternaus/kaggle_dstl_submission#5]
Dear all,

when I try to perform a prediction on the buildings (after the training) I get the following issue:

Using TensorFlow backend.
2017-12-04 14:24:44.615883: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2
  0%|          | 0/425 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/apache/kaggle_dstl_submission/src/make_prediction_cropped_buildings.py", line 95, in <module>
    result += [(image_id, mask_channel + 1, mask2poly(new_mask, threashold, x_scaler, y_scaler))]
  File "/home/apache/kaggle_dstl_submission/src/extra_functions.py", line 125, in mask2polygons_layer
    contours, hierarchy = cv2.findContours(((mask == 1) * 255).astype(np.uint8), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_TC89_KCOS)
ValueError: too many values to unpack

Can you please help?

Bests
G.

**Comment by degiorgig** [comment]
btw do you have any python 3.x version?

thanks 
G.

**Comment by johnny-salz** [comment]
Probably cv2.findContours returns no contours or hierarchy. Try to change this line like 
some_var = cv2.findContours(((mask == 1) * 255).astype(np.uint8), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_TC89_KCOS)
print(some_var)
And see what's happening there

**Comment by johnny-salz** [comment]
I was using Python 3 when we are in DSTL's competition AFAIR there was no problems besides occasional print statement here or there

**Comment by degiorgig** [comment]
Thank you I made it working by changing some method that has a new signature in python 3.

**Comment by bahmed11** [comment]
How did you fix the problem?
