### ISSUE TITLE
Dimension of the traning set images

### ISSUE THREAD

**Issue by degiorgig** [ternaus/kaggle_dstl_submission#9]
Dear all,
I see that in the code the img_rows and img_cols is set to 112, has that a special meaning or is it the best value that you found during the training?

Thanks
G.

**Comment by ternaus** [comment]
It was not, probably, the best. I would believe that bigger is better and in the other Segmentation problem, I used full resolution images (1920x1280).

At that time it was the maximum resolution that we could fit in our GPUs
